MSG0 = "Introdueix el nom del fitxer:\n"
MSG1 = "Ja existeix, vols sobreescriure'l? [1.Sí-0.No]:\n"
MSG2 = "Curs: "
MSG3 = "Aula: "
MSG4 = "Número d'alumnes: "
MSG5 = "Número de professors: "
MSG6 = "Hora: "
MSG7 = "Nom del professor/a: "
MSG8 = "Assignatura: "
MSG9 = "Temps que ha estat oberta la porta principal (minuts): "
MSG10 = "Temps que ha estat tancada la porta principal (minuts): "
MSG11 = "Temps que ha estat oberta la porta secundària (minuts): "
MSG12 = "Temps que ha estat tancada la porta secundària (minuts): "
MSG13 = "Temps que han estat obertes les finestres externes (minuts): "
MSG14 = "Temps que han estat tancades les finestres externes (minuts): "
MSG15 = "Temps que han estat obertes les finestres internes (minuts): "
MSG16 = "Temps que han estat tancades les finestres internes (minuts): "
MSG17 = "Heu tingut ventilació creuada? (Que estigui obertes finestres exteriors i porta o finestres " \
        "interiors)[1.Sí-0.No]: "
MSG18 = "Introdueix el CO²: "
MSG19 = "Introdueix la temperatura: "
MSG20 = "Introdueix la humitat: "


NO_ERROR = "El registre s'ha inserit correctament.\n"
ERROR1 = "No s'ha trobat el fitxer.\n"
ERROR2 = "No s'ha pogut inserir el registre.\n"

AUX = "Vols continuar introduïnt registres [1.Sí-0.No] \n"
DIA = "Dia [DD]: "
MES = "Mes [MM]: "
ANY = "Any [YYYY]: "
HORA = "Introdueix l'hora: "
MIN = "Introdueix els minuts"
PORTA = "Hi ha porta secundària [1.Sí-0.No]: "
FIN1 = "Hi ha finestres externes [1.Sí-0.No]: "
FIN2 = "Hi ha finestres internes [1.Sí-0.No]: "

ROUTE = "./files/"
EXT1 = ".txt"
EXT2 = ".csv"

MENU = "MENÚ\n1.Llegir fitxer\n2.Afegir registres"
HEADER = "| Curs    | Aula | Nº d'alumnes | Nº de professors/es | Dia       | Hora de classe | Professor/a " \
         "| Assignatura | "
REGISTRE = "| Dia       | Hora  | CO² (ppm)  | Temp (ºC) | Humitat Relativa (%)| "
